name: story_view_app
description: Stories Feature like snap WA, INSTAGRAM.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # C
  camera: ^0.9.4+14
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0

  # D
  dio: ^4.0.0
  
  # F
  flutter_cache_manager: ^3.1.2
  file_picker: ^4.5.1

  # G
  get_it: ^7.2.0

  # H
  helpers: ^1.1.4

  # P
  photo_manager: ^1.3.10
  provider: ^6.0.1

  # M
  mime: ^1.0.1

  # S
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.13

  # U
  uuid: ^3.0.6

  # V
  video_player: ^2.2.5
  video_editor: ^1.3.1
  video_compress: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/